version: '3.2'

services:

  webserver:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../quacker:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - 8000:80

  php-fpm:
    build: php-fpm
    container_name: php-fpm
    working_dir: /var/www/html
    volumes:
      - ../quacker:/var/www/html

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  
  db:
    image: postgres
    restart: always
    container_name: pgsql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quackdb
    volumes:
      - ../dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
